services:

    # PHP service
    app:
        build: ./docker/php
        image: php
        container_name: php
        working_dir: /var/www/
        volumes:
            - ./project:/var/www
            - ./log/php:/srv/var/log
        networks:
            - network

    # MariaDB database service
    db:
        image: mariadb:10.3
        container_name: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql-init:/docker-entrypoint-initdb.d
        networks:
            - network

    # Adminer service
    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 8081:8080
        networks:
            - network
        depends_on:
            - db

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8000:80
        volumes:
            - ./project:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./log/nginx:/var/log/nginx/
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    db_data:
        driver: local
